[package]
name = "hacspec-xor"
version = "0.1.0"
authors = ["Lasse Letager Hanse <letager@cs.au.dk>"]
edition = "2018"

[lib]
path = "src/xor.rs"

[dependencies]
hacspec-lib = { path = "../../lib" }





