[package]
name = "hacspec-rsa-pkcs1"
version = "0.1.0"
authors = ["Malte Thomsen <malteut@gmail.com>", "Marcus Rasmussen <marcusjr@live.dk>", "Tobias Vestergaard <tsv2907@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/rsa-pkcs1.rs"

[dependencies]
hacspec-lib = { path = "../../lib" }
hacspec-sha256 = { path = "../sha256" }

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
glass_pumpkin = "1.0"
num-bigint="0.4.3"
