[package]
name = "hacspec-hkdf"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

[lib]
path = "src/hkdf.rs"

[dependencies]
hacspec-lib = { path = "../../lib" }
hacspec-hmac = { path = "../hmac" }
hacspec-sha256 = { path = "../sha256" }
