[package]
name = "tls_cryptolib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hacspec-lib = { path = "../../../lib", version = "0.1.0-beta.1" }
hacspec-sha256 = { path = "../../sha256" }
hacspec-curve25519 = { path = "../../curve25519" }
hacspec-chacha20poly1305 = { path = "../../chacha20poly1305" }
hacspec-chacha20 = { path = "../../chacha20" }
hacspec-poly1305 = { path = "../../poly1305" }
hacspec-hmac = { path = "../../hmac" }
hacspec-hkdf = { path = "../../hkdf" }
hacspec-ecdsa-p256-sha256 = { path = "../../ecdsa-p256-sha256" }
hacspec-p256 = { path = "../../p256" }
hacspec-aes = { path = "../../aes", version = "0.1.0" }
hacspec-gf128 = { path = "../../gf128", version = "0.1.0" }
hacspec-aes128-gcm = { path = "../../aes128-gcm", version = "0.1.0" }
