name: Coverage

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Cargo
        run: |
          cargo clean
          cargo install grcov
          cargo build --verbose
          cargo install --path language
          RUSTFLAGS="-C instrument-coverage" LLVM_PROFILE_FILE="%m.profraw" cargo test --test coverage
          grcov ./lib/ --binary-path ./target/debug/ -s ./lib/ -t lcov --branch --ignore-not-existing -o lcov.info
      - name: Report code coverage
        run: |
          sudo apt-get install lcov
          lcov --list lcov.info
